[package]
name = "plonky2-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2="0.1.2"
plonky2_ecdsa="0.1.0"
anyhow = "1"